feat: Add TS type definitions
mercurius-js/cache pull request #62
Opened 2022-01-14 12:54 UTC by radomird

I've added type definition file and also will be adding tests for them.

Closes #57 

WORK IN PROGRESS

2022-01-17 16:25 UTC, radomird commented
PR is ready for reviews.

2022-01-17 19:49 UTC, mcollina approved these changes
lgtm

2022-01-17 19:52 UTC, mcollina requested changes
This module adds the `app.graphql.cache` on top of mercurius. This should be typed too.

2022-01-18 12:06 UTC, radomird commented
I've exposed the `cache` on the plugin as requested.

2022-01-19 09:08 UTC, simone-sanfratello requested changes
nice work!

some fix for storage options needed, but really well done!

2022-01-19 09:08 UTC, simone-sanfratello commented on index.d.ts
> +export interface MercuriusCacheStorageOptions {
MercuriusCacheStorageOptions can be either MercuriusCacheStorageMemoryOptions or MercuriusCacheStorageRedisOptions

they are (sorry for jsdoc format)

```js

/**
 * @typedef StorageMemoryOptions
 * @property {?number} [size=1024]
 * @property {?Logger} [log]
 * @property {?boolean} [invalidation=false]
 */

/**
 * @typedef StorageRedisOptions
 * @property {!object} client
 * @property {?Logger} log
 * @property {?Object|boolean} [invalidation=false]
 * @property {?number} [invalidation.referencesTTL=60]
 */

```

2022-01-19 09:08 UTC, simone-sanfratello commented on index.d.ts
> +  invalidate?: boolean | { invalidate: boolean; referencesTTL: number };
invalidation?: boolean | { referencesTTL: number };

btw it's different between memory and redis, so I think a specific option type is better

2022-01-19 16:41 UTC, radomird commented on index.d.ts
> +  log?: string;
For the logger I've put `object` as I didn't want to add pino as a dependency (just for the types). In case you think we should, please let me know.

2022-01-19 17:09 UTC, simone-sanfratello approved these changes

2022-01-19 17:09 UTC, simone-sanfratello commented
lgtm
nice!

2022-01-19 17:10 UTC, simone-sanfratello commented on index.d.ts
> +  log?: string;
fine with object

2022-01-19 17:11 UTC, radomird commented
The PR is ready to be merged.

2022-01-19 18:17 UTC, merged