Refactored Error handling
mercurius-js/cache pull request #77
Opened 2022-02-03 10:06 UTC by sameer-coder

This PR tries to simplify the error handling in the code. I have tried to split the different conditionals into separate functions so that the code is more readable. Added some tests to ensure 💯 coverage

Closes #76

2022-02-03 10:46 UTC, mcollina reviewed
Good work! There are still a few bugs of the original implementation to fix.

2022-02-03 10:46 UTC, mcollina commented on index.js
> +      return null
This is not correct and a bug in the previous implementation. We should not catch this error nor invoke onError.

2022-02-03 10:46 UTC, mcollina commented on index.js
> +    }
This is not correct and a bug in the previous implementation. We should not catch this error nor invoke onError.

2022-02-03 16:11 UTC, simone-sanfratello requested changes

2022-02-03 16:11 UTC, simone-sanfratello commented on index.js
> +    if ((skip && (await skip(self, arg, ctx, info))) ||
```suggestion
  isSkipped = ((skip && (await skip(self, arg, ctx, info))) ||
  (policy && policy.skip && (await policy.skip(self, arg, ctx, info)))) 
```

2022-02-04 09:35 UTC, simone-sanfratello approved these changes

2022-02-05 13:10 UTC, merged